"""investigation llm usage and deep dive

Revision ID: 2f5c65991ae3
Revises: 7daa900f550e
Create Date: 2026-09-30 10:36:01.933249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401  (Vector type used by autogenerated migrations)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f5c65991ae3'
down_revision: Union[str, Sequence[str], None] = '7daa900f550e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('deep_dive_summary', sa.Text(), nullable=True))
    op.add_column('investigations', sa.Column('llm_usage', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigations', 'llm_usage')
    op.drop_column('investigations', 'deep_dive_summary')
    # ### end Alembic commands ###
