"""invoice upload order

Revision ID: 7daa900f550e
Revises: 850ffe6b87be
Create Date: 2026-09-30 10:09:48.429662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401  (Vector type used by autogenerated migrations)


# revision identifiers, used by Alembic.
revision: str = '7daa900f550e'
down_revision: Union[str, Sequence[str], None] = '850ffe6b87be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('upload_seq', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    op.create_unique_constraint('uq_invoices_upload_seq', 'invoices', ['upload_seq'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_invoices_upload_seq', 'invoices', type_='unique')
    op.drop_column('invoices', 'upload_seq')
    # ### end Alembic commands ###
