"""initial schema

Revision ID: 850ffe6b87be
Revises: 
Create Date: 2026-09-30 09:31:57.841537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401  (Vector type used by autogenerated migrations)
from sqlalchemy.dialects import postgresql

from trustagent.config import get_settings

# The embedding dimension follows config for a fresh database. For an existing
# database, trustagent.db.session.check_embedding_dimension() fails fast on a
# mismatch; changing the model then needs a new migration and a re-ingest.
EMBEDDING_DIM = get_settings().embedding_dim

# revision identifiers, used by Alembic.
revision: str = '850ffe6b87be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('tool_used', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_investigation_id'), 'audit_log', ['investigation_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.String(length=20), nullable=True),
    sa.Column('contract_id', sa.String(length=50), nullable=True),
    sa.Column('section', sa.String(length=300), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=EMBEDDING_DIM), nullable=False),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_doc_type'), 'document_chunks', ['doc_type'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_document_chunks_supplier_id'), 'document_chunks', ['supplier_id'], unique=False)
    op.create_index('ix_document_chunks_tsv', 'document_chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_table('policies',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('bank_account', sa.String(length=20), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('risk_status', sa.String(length=10), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_date', sa.Date(), nullable=True),
    sa.Column('verified_by', sa.String(length=200), nullable=True),
    sa.Column('expected_spend_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_spend_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.String(length=20), nullable=True),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('bank_account', sa.String(length=20), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_holder', sa.String(length=200), nullable=True),
    sa.Column('supplier_email', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('urgency', sa.String(length=10), nullable=False),
    sa.Column('source_filename', sa.String(length=300), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extraction_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_supplier_id'), 'invoices', ['supplier_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.String(length=20), nullable=False),
    sa.Column('invoice_id', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('bank_account', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_supplier_id'), 'transactions', ['supplier_id'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('invoice_id', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.String(length=30), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('ai_review_available', sa.Boolean(), nullable=True),
    sa.Column('approvals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_invoice_id'), 'investigations', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    op.create_index(op.f('ix_investigations_supplier_id'), 'investigations', ['supplier_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=50), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('indicator_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_investigation_id'), 'evidence', ['investigation_id'], unique=False)
    # ### end Alembic commands ###

    # The audit log is append-only, enforced by the database itself: even a
    # bug in application code cannot rewrite history.
    op.execute(
        """
        CREATE FUNCTION audit_log_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER audit_log_no_update_delete BEFORE UPDATE OR DELETE ON audit_log "
        "FOR EACH ROW EXECUTE FUNCTION audit_log_append_only()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_update_delete ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_investigation_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_investigations_supplier_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_invoice_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_transactions_supplier_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_invoices_supplier_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('suppliers')
    op.drop_table('policies')
    op.drop_index('ix_document_chunks_tsv', table_name='document_chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_document_chunks_supplier_id'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_embedding', table_name='document_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_doc_type'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_audit_log_investigation_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
