"""invoice document accounts

Revision ID: 94eafcfff3e1
Revises: a0945e6db5e8
Create Date: 2026-09-30 11:45:31.403165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401  (Vector type used by autogenerated migrations)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94eafcfff3e1'
down_revision: Union[str, Sequence[str], None] = 'a0945e6db5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('document_accounts', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'document_accounts')
    # ### end Alembic commands ###
