"""invoice number unique per supplier

Revision ID: a0945e6db5e8
Revises: 2f5c65991ae3
Create Date: 2026-09-30 11:40:34.074305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401  (Vector type used by autogenerated migrations)


# revision identifiers, used by Alembic.
revision: str = 'a0945e6db5e8'
down_revision: Union[str, Sequence[str], None] = '2f5c65991ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows used the supplier's number as their id: copy it across, then enforce NOT NULL.
    op.add_column('invoices', sa.Column('invoice_number', sa.String(length=50), nullable=True))
    op.execute("UPDATE invoices SET invoice_number = id")
    op.alter_column('invoices', 'invoice_number', nullable=False)
    op.create_unique_constraint('uq_invoices_supplier_number', 'invoices', ['supplier_id', 'invoice_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_invoices_supplier_number', 'invoices', type_='unique')
    op.drop_column('invoices', 'invoice_number')
    # ### end Alembic commands ###
